//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspiring.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LJson {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LJson() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inspiring.Json.Json.LJson", typeof(LJson).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read &apos;{0}&apos; because property &apos;{1}&apos; is missing or invalid{3}: {2}.
        /// </summary>
        internal static string ArgumentExceptionOnDeserialization {
            get {
                return ResourceManager.GetString("ArgumentExceptionOnDeserialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize to an object of type &apos;{0}&apos;. The value &apos;{1}&apos; for type property &apos;{2}&apos; is not a valid type name..
        /// </summary>
        internal static string Converter_InvalidDiscriminatorValue {
            get {
                return ResourceManager.GetString("Converter_InvalidDiscriminatorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize to an object of type &apos;{0}&apos;. For abstract types the type property &apos;{1}&apos; has to be set in the JSON..
        /// </summary>
        internal static string Converter_MissingDiscriminatorProperty {
            get {
                return ResourceManager.GetString("Converter_MissingDiscriminatorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Path &apos;{0}&apos;, line {1}, position {2}).
        /// </summary>
        internal static string PositionInfo {
            get {
                return ResourceManager.GetString("PositionInfo", resourceCulture);
            }
        }
    }
}
